service: web-scrapper
frameworkVersion: '3'
custom:
  tableName: 'scrape-data-${self:provider.stage}'
  tableIndex:  'urlIndex'
  apiGatewayCaching:
    enabled: true
    ttlInSeconds: 0
  
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UserTable", "Arn" ] }
        - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.tableName}/index/*
  environment:
    SCRAPE_DATA: ${self:custom.tableName}
    URL_INDEX: ${self:custom.tableIndex}
    
package:
  individually: true
  patterns:
    - 'node_modules/**'
  exclude:
    - '!test/**'

functions:  
  scrape:
    handler: app/handler.scrape
    events:
      - http:
          path: /scrapeData
          method: post
          caching:
            enabled: true
            ttlInSeconds: 120

plugins:
  - serverless-offline
  - serverless-api-gateway-caching
resources:
  Resources:
    UserTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: url
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ${self:custom.tableIndex}
            KeySchema:
              - AttributeName: url
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}








































































































